#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 8 -font 'Fira Sans 10' -xoffset 20 -yoffset 122 -width 20 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< "Lock|Logout|Reboot|Shutdown")"
            case "$MENU" in
                *Lock) betterlockscreen -s;;
                *Logout) i3-msg exit;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
